// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzijoehcBHRtWtVi8aWKq6AKxnmQfS824',
    appId: '1:912328525338:web:5ea1b3924faf13c4f073a3',
    messagingSenderId: '912328525338',
    projectId: 'wasfa-rx',
    authDomain: 'wasfa-rx.firebaseapp.com',
    storageBucket: 'wasfa-rx.firebasestorage.app',
    measurementId: 'G-XX2NTXFMGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2_DTCpDnwo9-ob4ZdiFb4OU2rNmJiZeg',
    appId: '1:912328525338:android:c8ef5041385bd466f073a3',
    messagingSenderId: '912328525338',
    projectId: 'wasfa-rx',
    storageBucket: 'wasfa-rx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUD9_q_XLK5Yc-hBbhdazd9O7r6TijJBw',
    appId: '1:912328525338:ios:fb01d6785f99594af073a3',
    messagingSenderId: '912328525338',
    projectId: 'wasfa-rx',
    storageBucket: 'wasfa-rx.firebasestorage.app',
    iosBundleId: 'kw.wasfa.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUD9_q_XLK5Yc-hBbhdazd9O7r6TijJBw',
    appId: '1:912328525338:ios:3366a4e9a1f5282bf073a3',
    messagingSenderId: '912328525338',
    projectId: 'wasfa-rx',
    storageBucket: 'wasfa-rx.firebasestorage.app',
    iosBundleId: 'com.example.wasfaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzijoehcBHRtWtVi8aWKq6AKxnmQfS824',
    appId: '1:912328525338:web:4e03ca3489e425b7f073a3',
    messagingSenderId: '912328525338',
    projectId: 'wasfa-rx',
    authDomain: 'wasfa-rx.firebaseapp.com',
    storageBucket: 'wasfa-rx.firebasestorage.app',
    measurementId: 'G-E86QFS1FY1',
  );
}
