import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'core/notifications/notification_service.dart';
import 'core/routing/app_router.dart';
import 'core/routing/app_routes.dart';
import 'core/theme/app_theme.dart';
import 'data/services/notification_history_store.dart';
import 'firebase_options.dart'; // generated by running `flutterfire configure` — see README
import 'state/address_state.dart';
import 'state/app_settings_state.dart';
import 'state/auth_state.dart';
import 'state/cart_state.dart';
import 'state/locale_state.dart';
import 'state/location_state.dart';
import 'state/nav_tab_state.dart';
import 'state/orders_state.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // Must be registered before runApp — this is what lets a data message
  // wake the app in the background/terminated state at all. Registering
  // the handler itself is cheap/synchronous — only the initialize() call
  // below is what can actually hang.
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  runApp(const WasfaApp());
  // NotificationService.instance.initialize() is deliberately NOT started
  // here anymore — see SplashScreen._boot(), which is where it's called
  // now.
  //
  // It used to fire right here, unawaited, immediately after runApp() —
  // which raced against the location permission request the splash
  // screen makes moments later. Android only allows one permission dialog
  // on screen at a time; when both landed together, whichever one lost
  // the race got silently cancelled by the OS. That alone would just mean
  // "permission denied" — except Geolocator.requestPermission() has a
  // known bug where, in exactly this situation, it never returns at all
  // instead of resolving to denied
  // (github.com/Baseflow/flutter-geolocator/issues/1378, unfixed as of
  // this writing). The result: the whole app hung on the splash screen
  // forever, with nothing in logcat except "Can request only one set of
  // permissions at a time" — no crash, no timeout, no error. Only showed
  // up on a real device / an emulator image with Play Services actually
  // installed, which is also why the original comment here only mentioned
  // Play-Services-missing emulators hanging — that was a real, separate
  // failure mode, just not the only one this needed to guard against.
  //
  // Starting it from the splash screen instead, after location's own
  // permission cycle has already resolved, means there's never a second
  // permission dialog in flight to collide with in the first place.
}

class WasfaApp extends StatelessWidget {
  const WasfaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // "Model" layer shared app-wide — CartState/OrdersState/AddressState
        // double as the app's cross-screen ViewModels (see README section
        // "Architecture notes"), while per-screen ViewModels in lib/viewmodels
        // hold state that's local to a single screen.
        ChangeNotifierProvider(create: (_) => LocaleState()),
        ChangeNotifierProvider(create: (_) => AuthState()..restore()),
        ChangeNotifierProvider(create: (_) => LocationState()),
        ChangeNotifierProvider(create: (_) => CartState()),
        ChangeNotifierProvider(create: (_) => OrdersState()),
        ChangeNotifierProvider(create: (_) => AddressState()),
        // Which of RootShell's 4 tabs is active — see NavTabState's doc for
        // why this lives here rather than as RootShell's own local State
        // (Store, pushed on top of RootShell, needs to switch tabs too).
        ChangeNotifierProvider(create: (_) => NavTabState()),
        // Not calling .load() for now — /app/settings isn't a real backend
        // endpoint yet (see AppSettingsState's doc). The team's checkout
        // API will provide this once it's ready; wire .load() back in
        // then. Payment methods just default to all 4 enabled until then.
        ChangeNotifierProvider(create: (_) => AppSettingsState()),
        // .value, not create — this is a singleton shared with
        // NotificationService's foreground/background handlers, which add
        // to it directly via NotificationHistoryStore.instance rather than
        // going through this Provider at all. Registering it here is only
        // so the bell icon's badge and the notifications list screen can
        // watch it reactively.
        ChangeNotifierProvider.value(value: NotificationHistoryStore.instance),
      ],
      child: MaterialApp(
        title: 'WASFA',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.light(),
        navigatorKey: NotificationService.instance.navigatorKey,
        initialRoute: Routes.splash,
        onGenerateRoute: AppRouter.onGenerateRoute,
      ),
    );
  }
}
