import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'core/notifications/notification_service.dart';
import 'core/routing/app_router.dart';
import 'core/routing/app_routes.dart';
import 'core/theme/app_theme.dart';
import 'data/services/notification_history_store.dart';
import 'firebase_options.dart'; // generated by running `flutterfire configure` — see README
import 'state/address_state.dart';
import 'state/app_settings_state.dart';
import 'state/auth_state.dart';
import 'state/cart_state.dart';
import 'state/locale_state.dart';
import 'state/location_state.dart';
import 'state/orders_state.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // Must be registered before runApp — this is what lets a data message
  // wake the app in the background/terminated state at all. Registering
  // the handler itself is cheap/synchronous — only the initialize() call
  // below is what can actually hang.
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  runApp(const WasfaApp());
  // NOT awaited before runApp(): NotificationService.initialize() calls
  // FirebaseMessaging.instance.requestPermission()/getInitialMessage(),
  // both of which go through Google Play Services under the hood on
  // Android. Most emulator images (anything not explicitly tagged "Google
  // Play", just "Google APIs") don't have Play Services installed, and
  // these calls can hang indefinitely with no exception, no timeout, and
  // no log output at all when it's missing — this used to be awaited
  // BEFORE runApp(), so that hang blocked Flutter from rendering anything
  // whatsoever, showing as "stuck on splash" forever with nothing in
  // logcat to explain why (a real device with Play Services, or a
  // "Google Play" emulator image, never hit this). Runs in the background
  // now — push notifications simply aren't wired up yet for the first
  // moment or two the app is open, which is a fine tradeoff since the UI
  // is fully usable immediately regardless of whether this ever
  // completes.
  NotificationService.instance.initialize();
}

class WasfaApp extends StatelessWidget {
  const WasfaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // "Model" layer shared app-wide — CartState/OrdersState/AddressState
        // double as the app's cross-screen ViewModels (see README section
        // "Architecture notes"), while per-screen ViewModels in lib/viewmodels
        // hold state that's local to a single screen.
        ChangeNotifierProvider(create: (_) => LocaleState()),
        ChangeNotifierProvider(create: (_) => AuthState()..restore()),
        ChangeNotifierProvider(create: (_) => LocationState()),
        ChangeNotifierProvider(create: (_) => CartState()),
        ChangeNotifierProvider(create: (_) => OrdersState()),
        ChangeNotifierProvider(create: (_) => AddressState()),
        // Not calling .load() for now — /app/settings isn't a real backend
        // endpoint yet (see AppSettingsState's doc). The team's checkout
        // API will provide this once it's ready; wire .load() back in
        // then. Payment methods just default to all 4 enabled until then.
        ChangeNotifierProvider(create: (_) => AppSettingsState()),
        // .value, not create — this is a singleton shared with
        // NotificationService's foreground/background handlers, which add
        // to it directly via NotificationHistoryStore.instance rather than
        // going through this Provider at all. Registering it here is only
        // so the bell icon's badge and the notifications list screen can
        // watch it reactively.
        ChangeNotifierProvider.value(value: NotificationHistoryStore.instance),
      ],
      child: MaterialApp(
        title: 'WASFA',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.light(),
        navigatorKey: NotificationService.instance.navigatorKey,
        initialRoute: Routes.splash,
        onGenerateRoute: AppRouter.onGenerateRoute,
      ),
    );
  }
}
